### ISSUE TITLE
Invitar a todo el equipo

### ISSUE THREAD

**Issue by nsdelgadov** [nsdelgadov/CaDCCAgile#1]

**Comment by nsdelgadov** [comment]
- [x] Ardila
- [x] Andrade
- [x] Ameriko
- [x] ClaudinPoonpin
- [x] Coni
- [ ] Pancho M
- [ ] Agustin Villena
- [x] Jonathan
- [x] Steffan Wiche
- [x] Torta
- [ ] Marcel

**Comment by ez2torta** [comment]
why would you not agregarme here

**Comment by Claudin** [comment]
Inviten a torta
