### ISSUE TITLE
Elaborar diseño para la página

### ISSUE THREAD

**Issue by ardilom** [nsdelgadov/CaDCCAgile#14]
Encargado de que haya un diseño tentativo para la página

------------------------ EDITADO ----------------------

- [ ] Consultar con diseñador (Kari/Cisneros)
- [ ] Implementar paleta de colores de CaDCC (principal: gris/blanco .  detalles: rojo/amarillo/azul)
- [ ] La página principal debe ser el blog con las entradas
- [ ] Eliminar las secciones no utilizadas del sistema

**Comment by nsdelgadov** [comment]
Le calzé la pega al memesquad, veré que responden mañana

**Comment by nsdelgadov** [comment]
Kari dice que apañar con el diseño, pero lo hablaré en persona para dejar la pega clara.
Pato nos puede apañar con el html y css
