### ISSUE TITLE
Crear Test de Mezzanine/Django

### ISSUE THREAD

**Issue by ardilom** [nsdelgadov/CaDCCAgile#15]
https://ide.c9.io/claudin/cadcc_agile

---------------------- EDITED ----------------------

- [ ] Testear que la página cargue
- [ ] Testear que el contenido se despliega
- [ ] Testear los links
- [ ] Testear que el link del CaDCC lleve a mezzanine

**Comment by ardilom** [comment]
claudin encargado de que alguien haga los tests

**Comment by ez2torta** [comment]
Qué tipo de tests vamos a hacer?

Integración?

De que si posteo algo quede en alguna parte?
