### ISSUE TITLE
Crear Templates Base

### ISSUE THREAD

**Issue by ardilom** [nsdelgadov/CaDCCAgile#19]
Crear templates base para página del CaDCC

**Comment by nsdelgadov** [comment]
Estamos usando Mezzanine en conjunto con su template básico. Se cierra el issue, cualquier otra alteracion va de acuerdo al issue de diseño #14

**Comment by nsdelgadov** [comment]
Estamos usando Mezzanine en conjunto con su template básico. Se cierra el issue, cualquier otra alteracion va de acuerdo al issue de diseño #14
