### ISSUE TITLE
Pasar a Draw.io los papeles

### ISSUE THREAD

**Issue by nsdelgadov** [nsdelgadov/CaDCCAgile#2]

**Comment by ardilom** [comment]
https://www.draw.io/?state=%7B%22ids%22:%5B%220Bw39RD-AoNsOUjM3bG9la0hsTlk%22%5D,%22action%22:%22open%22,%22userId%22:%22100897103342347381817%22%7D#G0Bw39RD-AoNsOUjM3bG9la0hsTlk
