### ISSUE TITLE
Documentar APIs importantes

### ISSUE THREAD

**Issue by ardilom** [nsdelgadov/CaDCCAgile#20]
Escribir en un documento información de las APIs de fb, twitter, ucursos y mezzanine para publicar en la página

**Comment by ez2torta** [comment]
Api de Facebook
https://pypi.python.org/pypi/facebook-sdk

Api de Twitter
https://github.com/bear/python-twitter
https://dev.twitter.com/oauth/overview/application-owner-access-tokens

Tb podría ser útil
https://roundteam.co/

**Comment by ez2torta** [comment]
Cerraré esta cuestión por duplica3.. siono
