### ISSUE TITLE
Página: crear formulario para ofertas de trabajo

### ISSUE THREAD

**Issue by ardilom** [nsdelgadov/CaDCCAgile#21]
en el sitio de django/mezzanine

**Comment by nsdelgadov** [comment]
Andrade me recomendó revisar la página de la bolsa de trabajo que ya existe, es: https://bolsadetrabajo.dcc.uchile.cl/enviar-oferta y me fijé en el formulario, podríamos replicarlo o usar uno de googleforms por ahora.

**Comment by nsdelgadov** [comment]
Link al formulario: https://docs.google.com/a/cadcc.cl/forms/d/e/1FAIpQLSeTg0F7FeekONsZo9kEzGZYvqguQFso9aQyveAkT1VWdQmddA/viewform
Lo hice en base al que hicieron la gente de la bolsa, @crandrade estuvo trabajando en ella el semestre pasado. Podríamos anexar el código a lo que han hecho.
