### ISSUE TITLE
Link a Páginas Informativas Importantes

### ISSUE THREAD

**Issue by crandrade** [nsdelgadov/CaDCCAgile#27]
Tener un link a las páginas importantes (ej: Cei, FECH) para informarse y recordar sólo las noticias más importantes (ej: elecciones)

**Comment by coniesco** [comment]
- Universidad de Chile  
  [Página Oficial](http://www.uchile.cl/)  
  [Facebook](https://www.facebook.com/uchile)
- Escuela de Ingeniería  
  [Página Oficial](http://escuela.ingenieria.uchile.cl/)  
  [Facebook](https://www.facebook.com/ingenieria.uchile)
- FECH  
  [Facebook](https://www.facebook.com/fech.uchile)
- CEI  
  [Facebook](https://www.facebook.com/cei.uchile)
- DCC  
  [Página Oficial](https://www.dcc.uchile.cl/)  
  [Facebook](https://www.facebook.com/DCC.UdeChile)
