### ISSUE TITLE
Investigar cómo ejecutar código después de la creación de cada Post

### ISSUE THREAD

**Issue by zenbaku** [nsdelgadov/CaDCCAgile#33]
Después de crear una publicación en la página, esta sólo queda registrada ahí.
Se desea propagar ese contenido a redes sociales de forma automática y así sólo tener que publicar en un lugar.

Investiguemos cómo ejecutar código Python (que, por ejemplo, use algún módulo para usar las APIs de Twitter y Facebook) después de que se publique cada Post y así compartir el contenido del post (título, cuerpo y URL).

**Comment by zenbaku** [comment]
Para esto se puede usar el módulo de signals de django (https://docs.djangoproject.com/en/1.10/topics/signals/) y así escuchar la señal `post_save` para ejecutar código después de que se haya guardado cada modelo.

Por otro lado, el modelo de mezzannine que nos interesa es `BlogPost`, ubicado en el módulo `mezzanine.blog.models`.

**Comment by zenbaku** [comment]
Cabe mencionar que la señal `post_save` se ejecuta cada vez que se **guarda** un modelo, así que habría que revisar dos cosas:
1. Que el post esté publicado y no en modo _draft_
2. Que sea una creación y no una edición (ya no que queremos compartir dos veces el mismo contenido)

**Comment by zenbaku** [comment]
Se creó una [rama](/nsdelgadov/CaDCCAgile/tree/feature/automatic_publishing) con una solución inicial (commit e033839c9a7d7e462bcd269a1af66523b10e243e)

**Comment by Claudin** [comment]
Para cuando se crea un post y se publica se tiene:

``` python
@receiver(post_save, sender=BlogPost)
def my_handler(sender, instance, created, **kwargs):
    if created and instance.status == 2:
        dostuff()
```

Para el caso en que un post pasa de drafted a published no se pueden ver los cambios (hice los tests pertinentes), es por eso que existen 2 soluciones: 
- sobreescribir el método save() del modelo
- crear un logger que vaya guardando el estado de los post creados/modificados

Yo me iría por el segundo
