### ISSUE TITLE
Publicar en facebook desde la plataforma

### ISSUE THREAD

**Issue by ardilom** [nsdelgadov/CaDCCAgile#37]
- [x] Investigar Factibilidad
- [ ] Documentar API
- [x] Postear mensaje de comunicaciones
- [ ] Medir tiempo

**Comment by ardilom** [comment]
- [ ] Investigar Factibilidad
- [ ] Postear mensaje de comunicaciones
- [ ] Medir tiempo

**Comment by nsdelgadov** [comment]
En este momento solo falta que el crosspost contenga texto y no solo un link.
