### ISSUE TITLE
Integración clase del 25 de Noviembre al Git

### ISSUE THREAD

**Issue by nsdelgadov** [nsdelgadov/CaDCCAgile#38]
Se requiere actualizar Github con las siguientes labores:

- [x] Issue1: Armar experimento para Twitter
- [x] Issue2: Linkear la página sostenida en Heroku al CaDCC
- [x] Issue3: Actualizar Pancarta
- [x] Issue4: Viralizar Pancarta (digitalizar a través de los canales de comunicacion)
- [x] Issue5: El crosspost a Fb desde Mezzanine debiera postear texto, y no solo un link.

**Comment by nsdelgadov** [comment]
Hay que conectar el Twitter al Iceberg.

**Comment by nsdelgadov** [comment]
@cescobarf : Issue1
@Turtol : Issue 3 y 4
@Claudin : Issue 5
@nsdelgadov : Issue 4, 2

**Comment by Turtol** [comment]
Los issues fueron creados y asignados. Se cierra el issue de crear issues =)
