### ISSUE TITLE
Buscar método para contar vistas

### ISSUE THREAD

**Issue by nsdelgadov** [nsdelgadov/CaDCCAgile#4]
Buscar forma de contar las visitas a los resúmenes y otras informaciones del área de comunicaciones.

**Comment by nsdelgadov** [comment]
https://github.com/nsdelgadov/CaDCCAgile/projects/1#card-658911
Para contar las visitas envié el resumen de esta semana a través del goo.gl .
Se diferenció el link entre u-cursos y facebook.

**Comment by ardilom** [comment]
se hizo con goo.gl
