### ISSUE TITLE
Armar el experimento para twitter.

### ISSUE THREAD

**Issue by Turtol** [nsdelgadov/CaDCCAgile#40]
Se busca investigar el impacto que tendrá la integración del sistema con Twitter.

Los usuarios de Twitter tienden a ser paralelos a los usuarios de facebook más que compartidos. Hay muchos profesores y ex-alumnos que prefieren esta red social. Hay noticias para ellos también. Buscamos entender el impacto mediático.

**Comment by coniesco** [comment]
Una revisión de los últimos tweets revela que en general son leídos por la mayoría de los seguidores (~350), y que tienen mucho más impacto cuando son de carácter informativo (asambleas, feria laboral, charlas ~300) que de otro tipo (los que alertaban del día del paseo con el logo ~80). Un punto importante es que cuando las actividades llaman la atención más allá de los alumnos o son de carácter importante por lo general son retweeteados, lo que ayuda a tener un impacto aún mayor, de una forma más simple que el "compartir" de Facebook.

Es importante notar que la cuenta es seguida por muchas cuentas externas a la universidad, como empresas, páginas de tecnología, gente random, otras universidades, etc., al contrario de la página en Facebook que es seguida mayoritariamente por alumnos y ex-alumnos. Por esta razón los números anteriores no dan una expresión real del impacto de la cuenta para el público que nos interesa alcanzar. 

Por último, un experimento podría ser linkear los tweets a la página del cadcc, no poniendo toda la información en el tweet (algo pequeño) y revisar cuántas personas siguen efectivamente el link; de esa forma tendremos números concretos de las personas que se interesan por el contenido que estamos publicando.

**Comment by Turtol** [comment]
Entonces las partes:

Experimento: Linkear los tweets a la pagina del cadcc, con comentarios pequeños.
Medición: Cuantas personas siguen efectivamente el link. Esto entrega numeros concretos.
Expectativa: Que las personas realmente interesadas sigan el link alimentando la cuenta de la página.

Fechas: Queremos poner en produccion todo este domingo. Debieramos comenzar a linkear todo de una vez, para ver cuantas personas alimentan la página desde FB. Esto debiera quedar en www.cadcc.cl

El feedback debiera estar usable el miercoles.
