### ISSUE TITLE
Publicar en Telegram desde la plataforma usando bit.ly

### ISSUE THREAD

**Issue by ajerezg** [nsdelgadov/CaDCCAgile#43]
Contar las vistas de telegram y los clicks de bit.ly.
Éxito con 50 clicks en bit.ly

**Comment by Turtol** [comment]
http://mezzanine.jupo.org/docs/packages.html

generate_short_url()  :
Returns a new short URL generated using bit.ly if credentials for the service have been specified.

**Comment by nsdelgadov** [comment]
Hay que pasar las keys de un acortador "oficial"
