### ISSUE TITLE
Hacer Formulario

### ISSUE THREAD

**Issue by nsdelgadov** [nsdelgadov/CaDCCAgile#6]
Hacer formulario para pedir ayuda con difundir información.
Hablar con la directiva :p

**Comment by coniesco** [comment]
Info del formulario:
https://github.com/nsdelgadov/CaDCCAgile/projects/1#card-670009

Formulario de Preprocesamiento:
Autor\* - Contacto - Título\* - Preámbulo - Contenido\* - Imagen - Link - Categoría\*

**Comment by coniesco** [comment]
Formulario listo:
https://docs.google.com/forms/d/e/1FAIpQLSfMP1BIsmcD0rD2mDTGw1q9UmIZqlVuEEyUOL5a0Gp3jKV0YA/viewform
